title: 都立西高アメリカンフットボール部 OWLS
description: 東京都立西高等学校アメリカンフットボール部 OWLS 公式HPです。試合情報、OB・OGの情報などを発信しています。
lang: ja_JP
url: https://www.nishi-owls.com
timezone: Asia/Tokyo

twitter:
  username: nishi__owls

collections:
  games:
    output: true
    permalink: /game/:year/:name.html
  game_years:
    output: true
    permalink: /game/:name/index.html
  messages:
    output: true
    permalink: /message/individual/:name.html
  posts:
    permalink: /topics/:year/:month-:day-:title:output_ext

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "game_years"
    values:
      layout: "game_year"
  - scope:
      path: ""
      type: "messages"
    values:
      layout: "message"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "topics"
  - scope:
      path: ""
    values:
      layout: "default"

liquid:
  strict_filters: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  hard_wrap: true

exclude:
  - assets_data/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
