title: 都立西高アメリカンフットボール部 OWLS
description: 東京都立西高等学校アメリカンフットボール部 OWLS 公式HPです。試合情報、OB・OGの情報などを発信しています。
lang: ja_JP
url: https://www.nishi-owls.com
timezone: Asia/Tokyo

twitter:
  username: nishi__owls

collections:
  games:
    output: true
    permalink: /game/:year/:name.html
  game_years:
    output: false
  messages:
    output: true
    permalink: /message/individual/:name.html
  posts:
    permalink: /topics/:year/:month-:day-:title:output_ext

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "messages"
    values:
      layout: "message"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "topics"
  - scope:
      path: ""
    values:
      layout: "default"

liquid:
  strict_filters: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

kramdown:
  hard_wrap: true

pagination:
  enabled: true

jekyll-archives:
  collection: "games"
  enabled: [year]
  layouts:
    year: game_year
  permalinks:
    year: '/game/:year/'

exclude:
  - _tools/
  - assets_data/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

special_subtitle:
  text: "&#x1F3C6;祝関東大会出場"
  link: "/topics/2025/05-11-buzan.html"
