title: 都立西高校アメリカンフットボール部 OWLS
description: 東京都立西高等学校アメリカンフットボール部 OWLS 公式HPです。試合情報、OB・OGの情報などを発信しています。
lang: ja_JP

twitter:
  username: nishi__owls

collections:
  games:
    output: true
  game_years:
    output: true

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "game_years"
    values:
      layout: "game_year"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - assets_data/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
