backend:
  name: git-gateway
  branch: netlify
  squash_merges: true

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    identifier_field: "cms_id"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # TODO this preview_path is not working... YMD is not taken from slug?
    preview_path: "topics/{{year}}/{{month}}-{{day}}-{{slug}}"
    path: "{{year}}/{{slug}}"
    summary: "{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Tag",
          name: "tags",
          widget: "select",
          options: ["visit-obog", "news"],
        }
      - { label: "URL string", name: "cms_id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          # TODO use `image` or hide this
          label: "Image for Web",
          name: "image",
          widget: "string",
          required: false,
        }
      - {
          label: "Article Description",
          name: "social_description",
          widget: "string",
          required: false,
        }
      - {
          # TODO use `image` or hide this
          label: "Image for SNS card",
          name: "social_image",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
